version: "3.8"
services:
#  modserver:
#    container_name: modserver
#    image: modserver
#    build:
#      context: ./data/modserver
#      dockerfile: Dockerfile
#    ports:
#      - "8089:8089"
##    volumes:
##    - ${MINECRAFT_HOME}/data/modserver/mods:/modserver/mods
#    restart: always

  #datacraft:
  #  image: itzg/minecraft-server:java16
  #  ports:
  #    - 25561:25565
  #  environment:
  #    TYPE: "PAPER"
  #    ICON: "http://clipart-library.com/new_gallery/57-579791_minecraft-steve-alabama.png"
  #    MOTD: "Data Craft. Data Craft. Craft Data. Data Craft."
  #    MODE: "survival"
  #    EULA: "TRUE"
  #    ENABLE_RCON: "true"
  #    RCON_PASSWORD: ${RCON_PASSWORD}
  #    RCON_PORT: 28016
  #  volumes:
  #  - ${HOME}/data/datacraft:/data
  #  restart: always

#  vanilla:
#    image: itzg/minecraft-server:java17
#    hostname: vanilla
#    ports:
#      - 25565:25565
#      - 28016:28016
#    environment:
##      LEVEL: "vanilla"
#      MEMORY: "2G"
#      TYPE: "VANILLA"
#      ICON: "http://clipart-library.com/new_gallery/57-579791_minecraft-steve-alabama.png"
#      MOTD: "Vanilla Season 1: Elijah's World!"
#      MODE: "survival"
#      EULA: "TRUE"
#      ENABLE_RCON: "true"
#      RCON_PASSWORD: ${RCON_PASSWORD}
#      RCON_PORT: 28016
#    tty: true
#    stdin_open: true
#    volumes:
#    - ${MINECRAFT_HOME}/data/vanilla:/data
#    restart: always

#  strawberry:
#    image: itzg/minecraft-server:java17
#    hostname: strawberry
#    ports:
#      - 25565:25565
#      - 28016:28016
#    environment:
#      MEMORY: "2G"
#      TYPE: "VANILLA"
#      ICON: "http://clipart-library.com/new_gallery/57-579791_minecraft-steve-alabama.png"
#      MOTD: "Vanilla Season 2: Gabe's World!"
#      MODE: "survival"
#      EULA: "TRUE"
#      ENABLE_RCON: "true"
#      RCON_PASSWORD: ${RCON_PASSWORD}
#      RCON_PORT: 28016
#    tty: true
#    stdin_open: true
#    volumes:
#    - ${MINECRAFT_HOME}/data/strawberry:/data
#    restart: always

#  creativeexploration:
#    image: itzg/minecraft-server:java17
#    hostname: creativeexploration
#    ports:
#      - 25568:25565
#      - 28019:28016
#    environment:
##      LEVEL: "vanilla"
#      INITIAL_DELAY: 200
#      MEMORY: "2G"
#      TYPE: "VANILLA"
#      ICON: "http://clipart-library.com/new_gallery/57-579791_minecraft-steve-alabama.png"
#      MOTD: "Creative Exploration!"
#      MODE: "creative"
#      EULA: "TRUE"
#      ENABLE_RCON: "true"
#      RCON_PASSWORD: ${RCON_PASSWORD}
#      RCON_PORT: 28016
#    tty: true
#    stdin_open: true
#    volumes:
#    - ${MINECRAFT_HOME}/data/creativeexploration:/data
#    restart: always

#  oneblockskyblock:
#    image: itzg/minecraft-server:java17
#    ports:
#      - 25566:25565
#      - 28017:28016
#    environment:
#      INITIAL_DELAY: 200
##      LEVEL: "oneblock"
##      MEMORY: "2G"
#      TYPE: "VANILLA"
#      ICON: "http://clipart-library.com/new_gallery/57-579791_minecraft-steve-alabama.png"
#      MOTD: "Vanilla Season 2: OneBlock-SkyBlock"
#      MODE: "survival"
#      EULA: "TRUE"
#      ENABLE_RCON: "true"
#      RCON_PASSWORD: ${RCON_PASSWORD}
#      RCON_PORT: 28016
#    tty: true
#    stdin_open: true
#    volumes:
#    - ${MINECRAFT_HOME}/data/oneblockskyblock:/data
#    restart: always

#  flatworld:
#    image: itzg/minecraft-server:java17
#    ports:
#      - 25567:25565
#      - 28018:28016
#    environment:
#      INITIAL_DELAY: 400
##      LEVEL: "flatworld"
##      MEMORY: "2G"
#      TYPE: "VANILLA"
#      ICON: "http://clipart-library.com/new_gallery/57-579791_minecraft-steve-alabama.png"
#      MOTD: "Vanilla Season 3: Flatworld"
#      MODE: "creative"
#      EULA: "TRUE"
#      ENABLE_RCON: "true"
#      RCON_PASSWORD: ${RCON_PASSWORD}
#      RCON_PORT: 28016
#    tty: true
#    stdin_open: true
#    volumes:
#    - ${MINECRAFT_HOME}/data/flatworld:/data
#    restart: always

#  creativeexploration:
#    image: itzg/minecraft-server:java17
#    ports:
#      - 25568:25565
#      - 28019:28016
#    environment:
#      INITIAL_DELAY: 600
##      LEVEL: "creativeexploration"
##      MEMORY: "2G"
#      TYPE: "VANILLA"
#      ICON: "http://clipart-library.com/new_gallery/57-579791_minecraft-steve-alabama.png"
#      MOTD: "Vanilla Season 3: Creative Exploration"
#      MODE: "creative"
#      EULA: "TRUE"
#      ENABLE_RCON: "true"
#      RCON_PASSWORD: ${RCON_PASSWORD}
#      RCON_PORT: 28016
#    tty: true
#    stdin_open: true
#    volumes:
#    - ${MINECRAFT_HOME}/data/creativeexploration:/data
#    restart: always





           #itzg/minecraft-server:java8-multiarch
#      TYPE: "CURSEFORGE"
#      CF_API_KEY: ${CF_API_KEY}
#      CF_SERVER_MOD: "http://192.168.1.119:8089/create-1.19.2-0.5.1.b.zip"
#"https://www.curseforge.com/api/v1/mods/328085/files/4550987/download"
#"https://files2.9minecraft.net/index.php?act=download&id=1664154925&hash=6491dd4d1a3ad"
#"https://files2.9minecraft.net/index.php?act=dl&id=1664154925"
#"/mods/create-1.19.2-0.5.1.b.jar"
#      TYPE: "FORGE"
#      VERSION: "1.19.2"
#      GENERIC_PACK: "http://192.168.1.119:8089/create-1.19.2-0.5.1.b.zip"

  chocolate:
    image: itzg/minecraft-server:java17
    hostname: chocolate
    ports:
      - 25565:25565
      - 28016:28016
    environment:
      INITIAL_DELAY: 300
      WHITELIST: "Pretsels,MisterSquidFu,rhadamanth"
      OPS: "Pretsels"
      TYPE: "FTBA"
      FTB_MODPACK_ID: 101
      FTB_MODPACK_VERSION_ID: 6503
      MEMORY: "6G"
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      DIFFICULTY: "hard"
      ICON: "http://clipart-library.com/new_gallery/57-579791_minecraft-steve-alabama.png"
      MOTD: "Season 2: Feed-the-Beast"
      MODE: "survival"
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 28016
    tty: true
    stdin_open: true
    volumes:
    - ${MINECRAFT_HOME}/data/chocolate:/data
    - ${MINECRAFT_HOME}/data/mods:/mods
    restart: always

#    #tinyblueworld:
#    #image: itzg/minecraft-server:java16
#    #ports:
#    #  - 25562:25565
#    #environment:
#    #  TYPE: "PAPER"
#    #  ICON: "https://image.freepik.com/free-vector/pixel-art-planet-earth_38133-5.jpg"
#    #  MOTD: "Tiny Blue World for FBKitten and Ruby"
#    #  MODE: "survival"
#    #  EULA: "TRUE"
#    #  ENABLE_RCON: "true"
#    #  RCON_PASSWORD: ${RCON_PASSWORD}
#    #  RCON_PORT: 28016
#    #volumes:
#    #- ${HOME}/data/tinyblueworld:/data
#    #restart: always

#  sambashare:
#    image: dperson/samba
#    user: "${UID}:${GID}"
#    ports:
#      - "137:137/udp"
#      - "138:138/udp"
#      - "139:139/tcp"
#      - "445:445/tcp"
#    stdin_open: true
#    tty: true
#    volumes:
#      - ${MINECRAFT_HOME}/data/:/mount
#    command: '-s "Minecraft Data;/mount;yes;no;no;${SMB_USER}" -u "${SMB_USER};${SMB_PASS}" -p'

#  backups:
#    image: itzg/mc-backup
#    # This needs to be set because backups use hostnames
#    hostname: backups
#    command: loop
#    restart: always
#    environment:
#      EULA: "TRUE"
#      BACKUP_METHOD: restic
#      BACKUP_INTERVAL: "3h"
#      INITIAL_DELAY: 500
#      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
#      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
#      AWS_DEFAULT_REGION: ${AWS_REGION}
#      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
#      RESTIC_FORGET_ARGS: ${RESTIC_FORGET_ARGS}
#      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
#      RCON_PASSWORD: ${RCON_PASSWORD}
#      RCON_PORT: 28016
#      RCON_HOST: vanilla
#    volumes:
#      - ${MINECRAFT_HOME}/data:/data:ro
#      - ${MINECRAFT_HOME}/backups:/backups
#      - ${MINECRAFT_HOME}/recover:/recover
